#!/bin/bash

#SBATCH -n 16
#SBATCH --time=800:00
#SBATCH --mem-per-cpu=4000
#SBATCH --tmp=4000
#SBATCH --job-name=dbcan
#SBATCH --output=/nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/Projects_NCCR/other/lheistinger/mating_screen/processing_bams.out
#SBATCH --error=/nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/Projects_NCCR/other/lheistinger/mating_screen/processing_bams.err

export OMP_NUM_THREADS=16
export PATH="/nfs/home/ansintsova/miniconda3/bin:$PATH"
source activate satay

output_dir=/nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/Projects_NCCR/other/lheistinger/mating_screen/merged_bam
bam_dir=/nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/Projects_NCCR/other/lheistinger/mating_screen/bam
int_files=$(ls /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/Projects_NCCR/other/lheistinger/Int*Off*.bed)
code_dir=/nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/Projects_NCCR/repos/barral_satay/code
samples=$(echo 1_{1..4}_unmated 2_{1..4}_mating1h 3_{1..4}_mating6h)

python $code_dir/src/process_satay_bams.py -s $samples --bam_directory $bam_dir -o $output_dir --interval_files $int_files  
  
